---
# 1. Configuración del Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-nodejs-deployment
  labels:
    app: devsu-nodejs
spec:
  replicas: 2 # Levantará 2 instancias de tu aplicación para alta disponibilidad
  selector:
    matchLabels:
      app: devsu-nodejs
  template:
    metadata:
      labels:
        app: devsu-nodejs
    spec:
      containers:
      - name: devsu-nodejs
        image: jgraziano/devsu-nodejs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
# 2. Configuración del Service para exponer la app
apiVersion: v1
kind: Service
metadata:
  name: devsu-nodejs-service
spec:
  type: LoadBalancer # Crea una IP externa accesible
  selector:
    app: devsu-nodejs
  ports:
    - port: 80         # Puerto expuesto al exterior
      targetPort: 8000 # Puerto interno del contenedor
